config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'tickets#index'

  resources :tickets, except: :destroy do
    member do
      patch :change_status
      patch :change_assignee
    end
    resources :replies, only: [:create]
  end

  get 'search', to: 'search#search'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.employee?
      can :create, Reply
      can [:read, :change_status, :change_assignee], Ticket
    elsif user.customer?
      can [:read, :create], Ticket
      can :update, Ticket, customer_email: user.email
    else
      can :read, :all
      can :create, Ticket
    end
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_one :user, as: :role, dependent: :destroy
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :tickets
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :replies, dependent: :destroy
  has_one :user, as: :role, dependent: :destroy
  belongs_to :department

  delegate :username, to: :user
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :employee
  belongs_to :ticket

  validates :body, :ticket_id, :employee_id, presence: true

  after_save :send_email

  delegate :username, to: :employee
  delegate :customer_email, to: :ticket

  private

  def send_email
    CustomerMailer.ticket_updates(self).deliver_now
  end
end

app/models/ticket.rb
require 'elasticsearch/model'

class Ticket < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  include AASM

  aasm whiny_transitions: false do
    state :waiting_for_staff, initial: true
    state :waiting_for_customer
    state :on_hold
    state :cancelled, after_enter: :reset_employee
    state :completed, after_enter: :reset_employee

    event :waiting_for_staff do
      transitions to: :waiting_for_staff
    end

    event :waiting_for_customer do
      transitions to: :waiting_for_customer
    end

    event :on_hold do
      transitions to: :on_hold
    end

    event :cancel do
      transitions to: :cancelled
    end

    event :complete do
      transitions to: :completed
    end
  end

  before_create :assign_uref

  has_many :replies, dependent: :destroy
  belongs_to :department
  belongs_to :employee

  delegate :username, to: :employee

  validates :customer_name, :customer_email, :subject, :body, :department_id, presence: true
  validates :customer_email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  scope :newest_first, -> { order('created_at desc') }
  scope :by_status, -> status do
    case status
    when 'new_tickets'     then waiting_for_staff
    when 'open_tickets'    then waiting_for_customer
    when 'on_hold_tickets' then on_hold
    when 'closed_tickets'  then where(aasm_state: [:cancelled, :completed])
    end  
  end

  def self.states_with_events
    aasm.states.map(&:name).zip(Ticket.aasm.events.map(&:name)).to_h
  end

  private

  def assign_uref
    begin
      self.uref = generate_uref
    end while Ticket.exists?(uref: uref)
  end

  def generate_uref
    "#{random_capital_chars(3)}-#{random_hex(1)}-#{random_capital_chars(3)}-#{random_hex(1)}-#{random_capital_chars(3)}"
  end

  def random_capital_chars(quantity)
    ('A'..'Z').to_a.sample(quantity).join
  end

  def random_hex(quantity)
    SecureRandom.hex(quantity)
  end

  def reset_employee
    self.update(employee_id: nil)
  end
end

Ticket.import force: true

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable
         
  belongs_to :role, polymorphic: true

  after_create :create_customer

  validates :username, :email, :password, presence: true
  validates :password, confirmation: true

  def employee?
    self.role_type == 'Employee'
  end

  def customer?
    self.role_type == 'Customer'
  end

  private

  def create_customer
    Customer.create.user = self unless self.role
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_path, alert: controller_name.singularize.capitalize << " cannot be found"
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  respond_to :html
  authorize_resource
  
  expose(:reply, attributes: :reply_params)
  expose(:replies)
  expose(:ticket)

  def create
    reply.ticket_id = params[:ticket_id]
    reply.employee = current_user.role
    respond_with ticket do |format|
      if reply.save
        flash[:success] = 'Reply was added successfully'
      else
        format.html { render 'tickets/show' }
      end
    end
  end

  private

  def reply_params
    params.require(:reply).permit(:body)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @tickets = []
    else
      @tickets = Ticket.search(params[:q][:search]).records.paginate(page: params[:page], per_page: 5)
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  respond_to :html
  authorize_resource

  after_filter :create_reply, only: [:change_status, :change_assignee]

  expose(:ticket, attributes: :ticket_params)
  expose(:tickets) { Ticket.by_status(params[:status]).includes(:department).paginate(page: params[:page], per_page: 5) }
  expose(:reply)   { Reply.new }
  expose(:replies) { Reply.includes(:user) }

  def create
    if ticket.save
      CustomerMailer.new_ticket_email(ticket).deliver_now
      flash[:success] = 'Ticket was created successfully'
    end
    respond_with ticket
  end

  def edit
    authorize! :edit, ticket
  end

  def update
    if ticket.save
      ticket.waiting_for_staff!
      flash[:success] = 'Ticket was updated successfully'
    end
    respond_with ticket
  end

  def change_status
    if ticket.send(Ticket.states_with_events[ticket_params[:aasm_state].to_sym]) && ticket.save
      new_status = ticket.aasm_state.humanize
      @reply_body = "Status was changed to #{new_status}"
      redirect_to ticket, success: 'Status was changed successfully'
    else
      flash.now[:alert] = 'Unable to change status. Please try again'
      render 'tickets/show'
    end
  end

  def change_assignee
    assignee = Employee.find(ticket_params[:employee_id])
    if ticket.update(employee: assignee)
      @reply_body = "Ticket was assigned to #{assignee.username}"
      redirect_to ticket, success: 'Assignee was changed successfully'
    else
      flash.now[:alert] = 'Unable to change assignee. Please try again'
      render 'tickets/show'
    end
  end

  private

  def ticket_params
    params.require(:ticket).permit(:customer_name, :customer_email, :employee_id, :aasm_state,
                                   :subject, :department_id, :body)
  end

  def create_reply
    Reply.create(employee: current_user.role, ticket: ticket, body: @reply_body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
  def employees_names
    Employee.includes(:user).map { |e| [e.username, e.id] }
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def ticket_urefs
    content_tag(:div, id: 'urefs', class: 'hidden') do
      Ticket.pluck(:uref).join(', ').html_safe
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OnApp Support
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .col-md-12
          .navbar-header
            %a.no-decoration{href: '/'}
              .title.navbar-brand OnApp Support
          .collapse.navbar-collapse#bs-example-navbar-collapse-1
            %ul.nav.navbar-nav.headers
              %li= link_to 'New Tickets',     tickets_path(status: 'new_tickets')
              %li= link_to 'Open Tickets',    tickets_path(status: 'open_tickets')
              %li= link_to 'On Hold Tickets', tickets_path(status: 'on_hold_tickets')
              %li= link_to 'Closed Tickets',  tickets_path(status: 'closed_tickets')
            .navbar-text.navbar-right.headers
              - if user_signed_in?
                %span Hello #{current_user.username}
                = link_to 'Sign out', destroy_user_session_path, method: :delete
              - else
                = link_to 'Sign in', new_user_session_path
                |
                = link_to 'Sign up', new_user_registration_path
            = simple_form_for :q, url: search_path, method: :get, html: {class: 'navbar-form navbar-right', role: 'search'} do |f|
              = f.input :search, label: false, required: false, placeholder: 'Search', class: 'form-control'
              = f.submit '', name: nil, style: 'display: none'
    .container-fluid
      .row
        .flash_messages= render 'shared/flash_messages' unless flash.empty?
        = yield
        = ticket_urefs
      %footer
        %p= "© #{Date.current.year} OnApp Support - All Rights Reserved"

app/views/replies/_form.html.haml
.form-group
  = simple_form_for reply, url: ticket_replies_path(ticket) do |f|
    = f.input :body, label: false, input_html: {rows: "5"}, placeholder: 'Enter reply...'
    = f.submit "Reply", class: 'btn btn-default btn-small'

app/views/replies/_replies.html.haml
.col-md-12
  %table.table.borderless
    %tr
      %td.vert-align
        %span Ticket was created
        %br
        %em= "#{ticket.customer_name}, #{ticket.created_at.strftime('%b %-m, %Y %T')}"
    - replies.each do |reply|
      %tr
        - cache reply do
          %td.vert-align
            = reply.body
            %br
            %em= "#{reply.username}, #{reply.created_at.strftime('%b %-m, %Y %T')}"

app/views/search/search.html.haml
.col-md-8.col-md-offset-2
  - if @tickets.empty?
    %h3 Nothing was found
  - else
    %h3= "#{pluralize(@tickets.count, 'ticket')} found:"
    %br
    %table.table.borderless
      %tr
        %th Reference
        %th Subject
        %th Status
        %th Created At
        %th Updated At
      - @tickets.each do |ticket|
        %tr
          %td.col-md-3.vert-align= ticket.uref
          %td.col-md-3.vert-align= link_to ticket.subject, ticket
          %td.vert-align= ticket.aasm_state.humanize
          %td.vert-align= ticket.created_at.strftime('%b %-m, %Y %T')
          %td.vert-align= ticket.updated_at.strftime('%b %-m, %Y %T')
    = will_paginate @tickets

app/views/shared/_employee_change.html.haml
.form-group
  = simple_form_for ticket, url: change_assignee_ticket_path(ticket), html: {class: 'form-inline'} do |f|
    = f.association :employee, collection: employees_names, label: false, include_blank: 'Set assignee'
    = f.submit 'Change assignee', class: 'btn btn-default btn-small'

app/views/shared/_flash_messages.html.haml
= flash_messages

app/views/shared/_status_change.html.haml
.form-group
  = simple_form_for ticket, url: change_status_ticket_path(ticket), html: {class: 'form-inline'} do |f|
    = f.input :aasm_state, collection: Ticket.aasm.states_for_select, include_blank: 'Set status', label: false
    = f.submit 'Change status', class: 'btn btn-default btn-small'

app/views/tickets/_form.html.haml
= f.input :customer_name, label: 'Your name'
= f.input :customer_email, label: 'Your email'
= f.association :department, prompt: 'Choose a department'
= f.input :subject
= f.input :body, label: 'Description', input_html: {rows: "5"}

app/views/tickets/_ticket.html.haml
%tr{class: ticket.aasm_state}
  - cache ticket do
    %td.col-md-1.vert-align= ticket.uref
    %td.col-md-2.vert-align= link_to ticket.subject, ticket
    %td.col-md-1.vert-align= ticket.customer_name
    %td.col-md-1.vert-align= ticket.customer_email
    %td.col-md-1.vert-align= ticket.department.name
    %td.col-md-3.vert-align= truncate ticket.body
    %td.col-md-1.vert-align= ticket.aasm_state.humanize
    %td.col-md-1.vert-align= ticket.created_at.strftime('%b %-d, %Y %T')
    %td.col-md-1.vert-align= ticket.updated_at.strftime('%b %-d, %Y %T')

app/views/tickets/edit.html.haml
.col-md-4.col-md-offset-4
  %h3 Edit ticket:
  .form-group
    = simple_form_for ticket do |f|
      = render partial: 'form', locals: {f: f}
      = f.submit "Update ticket", class: 'btn btn-default btn-small'

app/views/tickets/index.html.haml
.col-md-12
  - if can? :create, ticket
    = link_to 'Add Ticket', new_ticket_path, class: 'btn btn-primary btn-small pull-right button'
  %table.table
    %tr
      %th Reference
      %th Subject
      %th Customer Name
      %th Customer Email
      %th Department
      %th Description
      %th Status
      %th Created At
      %th Updated At
    = render tickets.newest_first
    = will_paginate tickets

app/views/tickets/new.html.haml
.col-md-4.col-md-offset-4
  %h3 New ticket:
  .form-group
    = simple_form_for ticket do |f|
      = render partial: 'form', locals: {f: f}
      = f.submit "Add ticket", class: 'btn btn-default btn-small'

app/views/tickets/show.html.haml
.col-md-8.col-md-offset-2
  - if can? :update, ticket
    = link_to 'Edit Ticket', edit_ticket_path(ticket), class: 'btn btn-primary btn-small pull-right'
  %h2= ticket.subject
  %p= "##{ticket.uref}"
  %span= "status: #{ticket.aasm_state.humanize}"
  
  - if ticket.employee.nil?
    %span= "| Unassigned"
  - else
    %span= "| assigned to #{ticket.username}"

  %p.ticket= ticket.body
  
  = render partial: 'shared/status_change' if can? :change_status, ticket
  = render partial: 'shared/employee_change' if can? :change_assignee, ticket
  = render partial: 'replies/form' if can? :create, reply
  %h3 ticket's history:
  = render partial: 'replies/replies', locals: {replies: ticket.replies.includes(:employee)}